using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float speed = 5f;
    public float jumpForce = 5f;
    public int health = 3;  // vida inicial

    public Transform groundCheck;
    public float groundCheckRadius = 0.2f;
    public LayerMask groundLayer;
    private bool isGrounded;

    private Rigidbody2D rb;
    private Animator anim;

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        anim = GetComponent<Animator>();
    }

    void Update()
    {
        // Movimiento lateral
        float moveX = Input.GetAxisRaw("Horizontal");
        rb.linearVelocity = new Vector2(moveX * speed, rb.linearVelocity.y);

        // Revisar si está en el suelo
        isGrounded = Physics2D.OverlapCircle(groundCheck.position, groundCheckRadius, groundLayer);

        // Salto
        if (Input.GetKeyDown(KeyCode.Space) && isGrounded)
        {
            rb.linearVelocity = new Vector2(rb.linearVelocity.x, jumpForce);
        }

        // Simular daño con Q
        if (Input.GetKeyDown(KeyCode.Q))
        {
            TakeDamage();
        }
    }

    void TakeDamage()
    {
        health--;

        if (health > 0)
        {
            anim.SetTrigger("Hurt");  // animación de recibir daño
        }
        else
        {
            anim.SetTrigger("Death");   // animación de muerte
            // Opcional: desactivar movimiento
            this.enabled = false;
        }
    }
}
